name: Ruby Gem

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build, Test & Publish
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        version: 2.7.x

    - name: bundle install
      run: |
        sudo apt-get -y install libpq-dev
        bundle install
        
    - name: migrate
      run: cd test/dummy && bundle exec rails db:migrate
      env:
        RAILS_ENV: test
        RAILS_DATABASE_USERNAME: postgres
        RAILS_DATABASE_PASSWORD: postgres
        RAILS_DATABASE: postgres

    - name: Test
      run: bundle exec rake test
      env:
        RAILS_DATABASE_USERNAME: postgres
        RAILS_DATABASE_PASSWORD: postgres
        RAILS_DATABASE: postgres

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
